# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResturantInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResturantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ResturantName', models.CharField(blank=True, default=b'', max_length=100)),
                ('OwnerName', models.CharField(blank=True, default=b'', max_length=100)),
                ('District', models.CharField(blank=True, default=b'Kathmandu', max_length=50)),
                ('Address', models.CharField(blank=True, default=b'Baneshwor', max_length=50)),
                ('Trial', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('CreatedAt',),
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
